from __future__ import annotations

import tempfile
import unittest
from dataclasses import replace
from pathlib import Path

from uv_studio.generation.jobs import GenerationJobManager
from uv_studio.generation.recovery import recover_interrupted_project_jobs
from uv_studio.production.commands import ProductionSemanticService
from uv_studio.projects.identity import STUDIO_COMPAT_RECIPE_ID, studio_project_extensions
from uv_studio.projects.models import ProjectReference
from uv_studio.projects.store import PROJECT_FILENAME, ProjectStore
from uv_studio.projects.transactions import ProjectUnitOfWork


class Stage19RedoOutputRecoveryTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.store = ProjectStore(Path(self.tmp.name) / "projects")
        self.project = self.store.create_project(
            title="Stage 19 redo output recovery",
            recipe_id=STUDIO_COMPAT_RECIPE_ID,
            extensions=studio_project_extensions("micro_drama"),
            project_id="prj_stage19_redo_output",
        )
        self.production = ProductionSemanticService(self.store)
        self.production.create_scene(
            self.project.project_id,
            scene_id="scene_redo_output",
            title="Redo output scene",
        )
        self.production.create_shot(
            self.project.project_id,
            shot_id="shot_redo_output",
            scene_id="scene_redo_output",
            intent="Preserve generated bytes across restart and Redo",
        )
        self.uow = ProjectUnitOfWork(self.store)

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def _register_output_and_take(self) -> tuple[ProjectReference, Path, bytes, str]:
        relative_path = (
            "artifacts/generated_attempt_0123456789abcdef0123456789abcdef.png"
        )
        output = self.store.resolve_project_file(
            self.project.project_id,
            relative_path,
            allowed_roots=("artifacts",),
        )
        payload = b"redo-owned-generated-output"
        output.write_bytes(payload)

        artifact = ProjectReference(
            id="artifact_redo_output",
            kind="image",
            path=relative_path,
            metadata={"stage19": "redo-output-recovery"},
        )
        project = self.store.load_project(self.project.project_id)
        updated = replace(project, artifacts=(*project.artifacts, artifact))
        self.uow.commit(
            self.project.project_id,
            command="generation.register_output",
            documents={PROJECT_FILENAME: updated.to_dict()},
        )

        take_id = "take_redo_output"
        self.production.register_take(
            self.project.project_id,
            take_id=take_id,
            shot_id="shot_redo_output",
            reference_id=artifact.id,
            label="Redo-owned output",
        )
        return artifact, output, payload, take_id

    def _undo_take_and_output(self) -> None:
        self.uow.undo(self.project.project_id)
        self.uow.undo(self.project.project_id)

    def test_restart_preserves_generated_bytes_owned_by_redo_branch(self) -> None:
        artifact, output, payload, take_id = self._register_output_and_take()
        self._undo_take_and_output()

        project = self.store.load_project(self.project.project_id)
        self.assertFalse(any(item.id == artifact.id for item in project.artifacts))
        state = self.production.state(self.project.project_id)
        self.assertFalse(any(take.take_id == take_id for take in state.takes))
        self.assertTrue(output.is_file())
        self.assertEqual(output.read_bytes(), payload)

        self.assertEqual(
            recover_interrupted_project_jobs(
                GenerationJobManager(self.store),
                self.project.project_id,
            ),
            (),
        )
        self.assertTrue(output.is_file())
        self.assertEqual(output.read_bytes(), payload)
        self.assertEqual(
            tuple(
                self.store.root.glob(
                    f".uv-recovered-orphan-{self.project.project_id}-*-{output.name}"
                )
            ),
            (),
        )

        self.uow.redo(self.project.project_id)
        self.uow.redo(self.project.project_id)

        restored = self.store.load_project(self.project.project_id)
        self.assertTrue(any(item.id == artifact.id for item in restored.artifacts))
        restored_state = self.production.state(self.project.project_id)
        restored_takes = [take for take in restored_state.takes if take.take_id == take_id]
        self.assertEqual(len(restored_takes), 1)
        self.assertEqual(restored_takes[0].reference_id, artifact.id)
        self.assertTrue(output.is_file())
        self.assertEqual(output.read_bytes(), payload)

    def test_new_commit_truncates_redo_protection_and_orphan_is_quarantined(self) -> None:
        _artifact, output, payload, _take_id = self._register_output_and_take()
        self._undo_take_and_output()

        self.production.create_scene(
            self.project.project_id,
            scene_id="scene_truncates_redo",
            title="Truncate redo",
        )
        self.assertFalse(self.uow.history(self.project.project_id).can_redo)

        self.assertEqual(
            recover_interrupted_project_jobs(
                GenerationJobManager(self.store),
                self.project.project_id,
            ),
            (),
        )
        self.assertFalse(output.exists())
        quarantined = tuple(
            self.store.root.glob(
                f".uv-recovered-orphan-{self.project.project_id}-*-{output.name}"
            )
        )
        self.assertEqual(len(quarantined), 1)
        self.assertEqual(quarantined[0].read_bytes(), payload)


if __name__ == "__main__":
    unittest.main()
