'use client';

import { Film, Loader2, Play, Plus, RefreshCw, Upload } from 'lucide-react';
import { useCallback, useEffect, useRef, useState } from 'react';
import { getUVProject, type ProjectReference } from '@/lib/projectsApi';
import { executeMusicAssemblyCommand, getMusicAssembly, getMusicDirection, projectVideoArtifactUrl, renderMusicVideo, uploadProjectVideoSource, type MusicAssemblyState, type MusicDirectionState } from '@/lib/musicVideoApi';

interface Props { projectId: string; onProjectChanged?: () => void | Promise<void>; }
interface Draft { sourceId: string; sourceStart: string; }
const sec = (us: number) => (us / 1_000_000).toFixed(3).replace(/\.000$/, '');
function toUs(value: string, field: string) { const n = Number(value.replace(',', '.')); if (!Number.isFinite(n) || n < 0) throw new Error(`${field}: укажите число секунд`); return Math.round(n * 1_000_000); }
function sourceName(source: ProjectReference) { const name = source.metadata.original_name; const duration = source.metadata.duration_us; const label = typeof name === 'string' && name.trim() ? name : source.path.split('/').at(-1) ?? 'Видео'; return typeof duration === 'number' ? `${label} · ${sec(duration)} с` : label; }

export function MusicAssemblyProductPanel({ projectId, onProjectChanged }: Props) {
  const fileRef = useRef<HTMLInputElement>(null);
  const [sources, setSources] = useState<ProjectReference[]>([]); const [direction, setDirection] = useState<MusicDirectionState | null>(null); const [assembly, setAssembly] = useState<MusicAssemblyState | null>(null); const [drafts, setDrafts] = useState<Record<string, Draft>>({}); const [rendered, setRendered] = useState<ProjectReference | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [warning, setWarning] = useState(false);
  const refresh = useCallback(async () => {
    const [project, dir] = await Promise.all([getUVProject(projectId), getMusicDirection(projectId)]); const videos = project.sources.filter(item => item.kind === 'video'); setSources(videos); setDirection(dir);
    let current: MusicAssemblyState | null = null; try { current = await getMusicAssembly(projectId); setWarning(false); } catch { setWarning(true); } setAssembly(current);
    if (dir) { const byShot = new Map((current?.bindings ?? []).map(binding => [binding.shot_id, binding])); setDrafts(previous => Object.fromEntries(dir.shots.map(shot => { const bound = byShot.get(shot.shot_id); const old = previous[shot.shot_id]; return [shot.shot_id, { sourceId: bound?.source_id ?? (old && videos.some(video => video.id === old.sourceId) ? old.sourceId : videos[0]?.id ?? ''), sourceStart: bound ? sec(bound.source_start_us) : old?.sourceStart ?? '0' }]; }))); } else { setDrafts({}); setAssembly(null); }
  }, [projectId]);
  useEffect(() => { const timer = window.setTimeout(() => { void refresh().catch(reason => setError(reason instanceof Error ? reason.message : 'Не удалось загрузить сборку')); }, 0); return () => window.clearTimeout(timer); }, [refresh]);
  const run = async (work: () => Promise<void>) => { setBusy(true); setError(null); setNotice(null); try { await work(); await refresh(); await onProjectChanged?.(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Операция не выполнена'); } finally { setBusy(false); } };
  const upload = (file: File) => run(async () => { await uploadProjectVideoSource(projectId, file); setNotice('Видео добавлено в медиатеку клипа.'); });
  const save = () => run(async () => { if (!direction) throw new Error('Сначала сохраните режиссёрский план.'); const assignments = direction.shots.map((shot,index) => { const draft = drafts[shot.shot_id]; if (!draft?.sourceId) throw new Error(`Кадр ${index+1}: выберите видео.`); return { shot_id: shot.shot_id, source_id: draft.sourceId, source_start_us: toUs(draft.sourceStart, `Кадр ${index+1}`) }; }); const result = await executeMusicAssemblyCommand(projectId, { command:'set_music_assembly', music_direction_revision_sha256: direction.revision_sha256, assignments }); if (!result.payload) throw new Error('Визуалы не сохранились.'); setAssembly(result.payload); setRendered(null); setNotice('Визуалы привязаны к кадрам.'); });
  const render = () => run(async () => { if (!assembly) throw new Error('Сначала сохраните визуалы.'); const result = await renderMusicVideo(projectId, assembly.revision_sha256); if (!result.result.artifact) throw new Error('Готовый файл не создан.'); setRendered(result.result.artifact); setNotice('Клип собран с мастер-аудио.'); });
  return <section className="rounded-2xl border border-[var(--uv-border)] bg-[var(--uv-surface-0)] p-5 sm:p-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-400/10 text-violet-300"><Film size={18}/></span><div><h2 className="text-lg font-medium text-zinc-100">Визуалы и сборка</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-zinc-600">Для каждого запланированного кадра выберите видео и точку начала. Мастер-песня остаётся единственной аудиодорожкой клипа.</p></div></div><button type="button" disabled={busy} onClick={() => void refresh()} className="secondary"><RefreshCw size={13}/> Обновить</button></div>
    {error&&<Banner tone="error">{error}</Banner>}{notice&&<Banner tone="ok">{notice}</Banner>}
    <div className="mt-5 flex items-center gap-3"><input ref={fileRef} type="file" accept="video/*" aria-label="Видео для Music Assembly" className="hidden" onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file)}}/><button type="button" disabled={busy} onClick={()=>fileRef.current?.click()} className="secondary"><Upload size={13}/> Добавить видео</button><span className="text-xs text-zinc-700">В медиатеке: {sources.length}</span></div>
    {!direction?<div className="mt-5 rounded-xl border border-dashed border-[var(--uv-border)] p-5 text-sm text-zinc-700">Сначала сохраните режиссёрский план во вкладке «Музыка и план».</div>:<div className="mt-6 space-y-3">{direction.shots.map((shot,index)=>{const draft=drafts[shot.shot_id]??{sourceId:'',sourceStart:'0'};return <div key={shot.shot_id} className="rounded-2xl border border-[var(--uv-border)] bg-[var(--uv-surface-1)] p-4"><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(220px,1fr)_150px] lg:items-end"><div><p className="text-sm font-medium text-zinc-200">Кадр {index+1}</p><p className="mt-1 text-[11px] text-zinc-700">{sec(shot.start_us)}–{sec(shot.end_us)} с</p><p className="mt-2 text-xs text-zinc-500">{shot.intent}</p></div><label className="text-[11px] text-zinc-600">Видео<select aria-label={`Видеоисточник музыкального кадра ${index+1}`} value={draft.sourceId} onChange={e=>setDrafts(c=>({...c,[shot.shot_id]:{...draft,sourceId:e.target.value}}))} className="field mt-1.5"><option value="">Выберите видео</option>{sources.map(source=><option key={source.id} value={source.id}>{sourceName(source)}</option>)}</select></label><label className="text-[11px] text-zinc-600">Начало в видео, с<input aria-label={`Начало источника музыкального кадра ${index+1}`} value={draft.sourceStart} onChange={e=>setDrafts(c=>({...c,[shot.shot_id]:{...draft,sourceStart:e.target.value}}))} className="field mt-1.5"/></label></div></div>})}<button type="button" disabled={busy||sources.length===0||direction.shots.some(shot=>!drafts[shot.shot_id]?.sourceId)} onClick={save} className="primary">{busy?<Loader2 size={14} className="animate-spin"/>:<Plus size={14}/>} Сохранить визуалы</button></div>}
    {warning&&<div className="mt-4 rounded-xl border border-amber-400/15 bg-amber-400/[0.05] p-3 text-xs text-amber-100/75">Режиссёрский план изменился. Проверьте привязки и сохраните их заново.</div>}
    {assembly&&<div className="mt-5 rounded-2xl border border-[var(--uv-border)] bg-[var(--uv-surface-1)] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-sm font-medium text-zinc-200">Собрать клип</h3><p className="mt-1 text-xs text-zinc-700">Все кадры привязаны. Можно собрать текущую версию.</p></div><button type="button" disabled={busy} onClick={render} className="primary">{busy?<Loader2 size={14} className="animate-spin"/>:<Play size={14}/>} Собрать клип</button></div>{rendered&&<a href={projectVideoArtifactUrl(projectId,rendered.id)} target="_blank" rel="noreferrer" className="mt-4 inline-flex rounded-lg border border-emerald-400/20 px-3 py-2 text-xs text-emerald-200">Открыть готовый клип</a>}</div>}
    <style jsx global>{`.field{width:100%;border:1px solid var(--uv-border);border-radius:9px;background:rgba(0,0,0,.18);padding:9px 10px;color:#d4d4d8;font-size:12px}.primary,.secondary{display:inline-flex;align-items:center;justify-content:center;gap:6px;border-radius:9px;font-size:11px}.primary{background:var(--uv-accent);padding:10px 14px;color:#090a0d;font-weight:650}.secondary{border:1px solid var(--uv-border-strong);padding:8px 11px;color:#a1a1aa}.primary:disabled{background:#27272a;color:#52525b}`}</style>
  </section>;
}
function Banner({tone,children}:{tone:'ok'|'error';children:React.ReactNode}){return <div className={`mt-4 rounded-xl border px-4 py-3 text-sm ${tone==='ok'?'border-emerald-400/20 bg-emerald-400/[0.06] text-emerald-200':'border-rose-400/20 bg-rose-400/[0.06] text-rose-200'}`}>{children}</div>}
