'use client';

import { CheckCircle2, ExternalLink, RefreshCw, ShieldCheck } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { getUVProject, type ProjectReference } from '@/lib/projectsApi';
import { projectVideoArtifactUrl } from '@/lib/musicVideoApi';
import { getMusicVideoReview, submitMusicVideoReview, type MusicVideoReviewOutcome, type MusicVideoReviewState, type MusicVideoReviewVerdict } from '@/lib/musicVideoReviewApi';

interface Props { projectId: string; refreshRevision?: number; onProjectChanged?: () => void | Promise<void>; }
const verdictLabels: Record<MusicVideoReviewVerdict,string>={approved:'Одобрить',needs_revision:'На доработку',rejected:'Отклонить'};
const outcomeLabels: Record<MusicVideoReviewOutcome,string>={pass:'Соответствуют',uncertain:'Не уверен',fail:'Не соответствуют'};
function sec(us:number){return (us/1_000_000).toFixed(1).replace(/\.0$/,'')}
function isRender(reference:ProjectReference){return reference.kind==='video'&&reference.metadata.lifecycle==='music_video_render'}

export function MusicVideoReviewProductPanel({projectId,refreshRevision=0,onProjectChanged}:Props){
  const[artifacts,setArtifacts]=useState<ProjectReference[]>([]);const[artifactId,setArtifactId]=useState('');const[review,setReview]=useState<MusicVideoReviewState|null>(null);const[verdict,setVerdict]=useState<MusicVideoReviewVerdict>('approved');const[transitionOutcome,setTransitionOutcome]=useState<MusicVideoReviewOutcome>('pass');const[note,setNote]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[warning,setWarning]=useState(false);const[notice,setNotice]=useState<string|null>(null);
  const refresh=useCallback(async()=>{const project=await getUVProject(projectId);const rendered=project.artifacts.filter(isRender);setArtifacts(rendered);setArtifactId(current=>rendered.some(item=>item.id===current)?current:rendered.at(-1)?.id??'');try{const current=await getMusicVideoReview(projectId);setReview(current);setWarning(false);if(current){setArtifactId(current.artifact_id);setVerdict(current.verdict);setTransitionOutcome(current.transition_outcome);setNote(current.note??'')}}catch{setReview(null);setWarning(true)}},[projectId]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void refresh().catch(reason=>setError(reason instanceof Error?reason.message:'Не удалось загрузить проверку'))},0);return()=>window.clearTimeout(timer)},[refresh,refreshRevision]);
  const selected=useMemo(()=>artifacts.find(item=>item.id===artifactId)??null,[artifacts,artifactId]);
  const excerpt=selected?.metadata.song_excerpt;const excerptDuration=typeof excerpt==='object'&&excerpt!==null&&typeof(excerpt as Record<string,unknown>).start_us==='number'&&typeof(excerpt as Record<string,unknown>).end_us==='number'?((excerpt as Record<string,number>).end_us-(excerpt as Record<string,number>).start_us):null;
  const submit=async()=>{if(!artifactId)return;setBusy(true);setError(null);setNotice(null);try{const saved=await submitMusicVideoReview(projectId,{artifact_id:artifactId,verdict,transition_outcome:transitionOutcome,note:note.trim()||null});setReview(saved);setWarning(false);setNotice('Проверка сохранена.');await onProjectChanged?.()}catch(reason){setError(reason instanceof Error?reason.message:'Проверка не сохранилась')}finally{setBusy(false)}};
  return <section className="rounded-2xl border border-[var(--uv-border)] bg-[var(--uv-surface-0)] p-5 sm:p-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-400/10 text-violet-300"><ShieldCheck size={18}/></span><div><h2 className="text-lg font-medium text-zinc-100">Проверка клипа</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-zinc-600">Посмотрите собранную версию, оцените переходы и сохраните решение. Измеримые проверки показаны рядом, но финальное визуальное решение остаётся за вами.</p></div></div><button type="button" disabled={busy} onClick={()=>void refresh()} className="secondary"><RefreshCw size={13}/> Обновить</button></div>
    {error&&<Banner tone="error">{error}</Banner>}{notice&&<Banner tone="ok">{notice}</Banner>}
    {artifacts.length===0?<div className="mt-5 rounded-xl border border-dashed border-[var(--uv-border)] p-5 text-sm text-zinc-700">Сначала соберите клип во вкладке «Сборка».</div>:<div className="mt-6 grid gap-4 xl:grid-cols-[minmax(0,1.1fr)_minmax(320px,.9fr)]">
      <div className="rounded-2xl border border-[var(--uv-border)] bg-[var(--uv-surface-1)] p-4"><label className="text-[11px] text-zinc-600">Версия клипа<select aria-label="Финальный Music Video рендер" value={artifactId} onChange={e=>setArtifactId(e.target.value)} className="field mt-1.5">{artifacts.map((item,index)=><option key={item.id} value={item.id}>Версия {index+1}</option>)}</select></label>{selected&&<div className="mt-3 flex flex-wrap gap-3"><a href={projectVideoArtifactUrl(projectId,selected.id)} target="_blank" rel="noreferrer" className="secondary"><ExternalLink size={13}/> Открыть клип</a>{excerptDuration!==null&&<span className={`rounded-full px-2.5 py-1 text-[10px] ${excerptDuration>=20_000_000&&excerptDuration<=30_000_000?'bg-emerald-400/10 text-emerald-300':'bg-amber-400/10 text-amber-200'}`}>{sec(excerptDuration)} с · {excerptDuration>=20_000_000&&excerptDuration<=30_000_000?'целевой диапазон':'вне диапазона 20–30 с'}</span>}</div>}</div>
      <div className="rounded-2xl border border-[var(--uv-border)] bg-[var(--uv-surface-1)] p-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-[11px] text-zinc-600">Решение<select aria-label="Вердикт финальной Music Video проверки" value={verdict} onChange={e=>setVerdict(e.target.value as MusicVideoReviewVerdict)} className="field mt-1.5">{Object.entries(verdictLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-[11px] text-zinc-600">Переходы<select aria-label="Проверка переходов Music Video" value={transitionOutcome} onChange={e=>setTransitionOutcome(e.target.value as MusicVideoReviewOutcome)} className="field mt-1.5">{Object.entries(outcomeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><label className="mt-3 block text-[11px] text-zinc-600">Заметка<textarea aria-label="Заметка финальной Music Video проверки" value={note} onChange={e=>setNote(e.target.value)} rows={3} className="field mt-1.5"/></label><button type="button" disabled={busy||!artifactId} onClick={()=>void submit()} className="primary mt-3"><CheckCircle2 size={14}/> Сохранить проверку</button></div>
    </div>}
    {warning&&<div className="mt-4 rounded-xl border border-amber-400/15 bg-amber-400/[0.05] p-3 text-xs text-amber-100/75">Клип или его подготовка изменились. Старое решение больше не считается проверкой текущей версии.</div>}
    {review&&<div className="mt-5"><h3 className="text-xs uppercase tracking-[0.14em] text-zinc-700">Что проверено</h3><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><Evidence label="Длительность" outcome={review.evidence.release_duration.outcome}/><Evidence label="Ритм" outcome={review.evidence.rhythm_alignment.outcome}/><Evidence label="Мастер-аудио" outcome={review.evidence.master_audio_binding.outcome}/><Evidence label="Визуальная сборка" outcome={review.evidence.visual_assembly_binding.outcome}/><Evidence label="Переходы" outcome={review.transition_outcome}/></div><div className={`mt-4 inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm ${review.verdict==='approved'?'border-emerald-400/20 bg-emerald-400/[0.06] text-emerald-200':review.verdict==='needs_revision'?'border-amber-400/20 bg-amber-400/[0.06] text-amber-100':'border-rose-400/20 bg-rose-400/[0.06] text-rose-200'}`}><CheckCircle2 size={14}/>{review.verdict==='approved'?'Текущая версия одобрена':review.verdict==='needs_revision'?'Текущая версия отправлена на доработку':'Текущая версия отклонена'}</div></div>}
    <style jsx global>{`.field{width:100%;border:1px solid var(--uv-border);border-radius:9px;background:rgba(0,0,0,.18);padding:9px 10px;color:#d4d4d8;font-size:12px}.primary,.secondary{display:inline-flex;align-items:center;justify-content:center;gap:6px;border-radius:9px;font-size:11px}.primary{background:var(--uv-accent);padding:10px 14px;color:#090a0d;font-weight:650}.secondary{border:1px solid var(--uv-border-strong);padding:8px 11px;color:#a1a1aa}`}</style>
  </section>;
}
function Evidence({label,outcome}:{label:string;outcome:string}){const pass=outcome==='pass',uncertain=outcome==='uncertain';return <div className={`rounded-xl border p-3 ${pass?'border-emerald-400/15 bg-emerald-400/[0.045]':'border-amber-400/15 bg-amber-400/[0.045]'}`}><p className="text-[10px] uppercase text-zinc-700">{label}</p><p className={`mt-1.5 text-xs ${pass?'text-emerald-300':'text-amber-200'}`}>{pass?'Готово':uncertain?'Не уверен':'Требует внимания'}</p></div>}
function Banner({tone,children}:{tone:'ok'|'error';children:React.ReactNode}){return <div className={`mt-4 rounded-xl border px-4 py-3 text-sm ${tone==='ok'?'border-emerald-400/20 bg-emerald-400/[0.06] text-emerald-200':'border-rose-400/20 bg-rose-400/[0.06] text-rose-200'}`}>{children}</div>}
